name: Issue Report
description: File an issue
title: "[bug] <title>"
labels: ["bug", "triage", "team: studio"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more info you provide, the more we can help you.

  - type: textarea
    attributes:
      label: Current/Expected Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false

  - type: input
    attributes:
      label: Link to Docs Page (if applicable)
      description: This makes investigating issues and helping you out significantly easier!
      placeholder: https://docs.livepeer.org
    validations:
      required: false
